HairCare.Web/Controllers/AskExpertController.cs
using HairCare.DB;
using HairCare.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HairCare.Web.Controllers
{
    public class AskExpertController : BaseController
    {

        public ActionResult Index()
        {
            srvAskExpert srv = new srvAskExpert();
            return View(srv.GetAllActive());
        }

        public ActionResult Form()
        {
            ViewBag.IsSent = false;
            return View();
        }

        [HttpPost]
        public ActionResult Form(AskExpert model)
        {            
            srvAskExpert srv = new srvAskExpert();
            model.SenderIP = HttpContext.Request.UserHostAddress;
            srv.SaveAsNotActive(model);
            ViewBag.IsSent = true;
            return View();
        }

        public PartialViewResult MainPart()
        {
            return PartialView();
        }
	}
}

HairCare.Web/Controllers/ContentController.cs
using HairCare.Com;
using HairCare.Service;
using HairCare.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HairCare.Web.Controllers
{
    public class ContentController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail(int Id)
        {
            srvContent service = new srvContent();

            var model = service.GetContentDetail(Id);
                        

            if (model != null)
                return View(model);

            return GoHomePage();
        }

        public PartialViewResult NextContent(int CurrContentId)
        {
            srvContent service = new srvContent();
            return PartialView(service.GetNextContent(CurrContentId, Vars.defaultNextContentCount));
        }

        public PartialViewResult Popular(int? ParentId)
        {
            srvContent service = new srvContent();
            var model = service.GetPopular(ParentId);

            return PartialView(model);
        }

        public PartialViewResult Recents()
        {
            srvContent service = new srvContent();
            var model = service.GetRecents();

            return PartialView(model);
        }


	}
}

HairCare.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HairCare.Service;
using System.Xml;
namespace HairCare.Web.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult HeroContents()
        {
            return PartialView();
        }

    }
}

HairCare.Web/Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HairCare.Web.Controllers
{
    public class InterviewController : Controller
    {
        public PartialViewResult MainPart()
        {
            return PartialView();
        }
	}
}

HairCare.Web/Controllers/TipsController.cs
using HairCare.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HairCare.Web.Controllers
{
    public class TipsController : Controller
    {
        //
        // GET: /Tips/
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult TipList()
        {
            srvContent srv = new srvContent();
            return PartialView(srv.GetContentByCatId(14));
        }

        public PartialViewResult MainPart()
        {
            return PartialView();
        }
	}
}

HairCare.Web/Views/Home/HeroContents.cshtml
<script>

    $(function () {

        initBannerSlider();

    });

    function initBannerSlider() {
        var sliderMainBanner = new MasterSlider();

        sliderMainBanner.control('bullets');

        sliderMainBanner.setup('mainBanner', {
            width: 1400,
            height: 400,
            space: 1,
            layout: 'fullwidth',
            loop: true,
            preload: 0,
            instantStartLayers: true,
            autoplay: true
        });
    }


</script>

<div class="main_banner_area">
    <div class="master-slider ms-skin-default" id="mainBanner">
        <!-- new slide -->
        <div class="ms-slide">
            <!-- slide background -->
            <img src="/scripts/masterslider/blank.gif" data-src="/images/content/1_b.png" alt="" />
            <a href="/detay/54/buklelerine-hayat-ver-kivircik-saclilar-icin-sac-bakim" data-ga="banner1-click-id-54"></a>

            <!-- slide text layer -->
            <div class="ms-layer ms-caption" style="bottom:0px; left:30px;">
                <div class="bannerCaption">
                    <h1>
                        BUKLELERİNE HAYAT 
                        VER
                    </h1>
                    <p>KIVIRCIK SAÇLAR İÇİN SAÇ BAKIMI</p>
                    <a class="detay2Bt" href="/detay/54/buklelerine-hayat-ver-kivircik-saclilar-icin-sac-bakim" data-ga="banner1-click-id-54"></a>
                </div>
            </div>
        </div>
        <!-- end of slide -->
        <!-- new slide -->
        <div class="ms-slide">
            <!-- slide background -->
            <img src="/scripts/masterslider/blank.gif" data-src="/images/content/2_b.png" alt="" />
            <a href="/detay/8/banyo-sanati-biraz-simarmak-herkesin" data-ga="banner2-click-id-8"></a>
            <!-- slide text layer -->
            <div class="ms-layer ms-caption" style="bottom:0px; left:30px; ">
                <div class="bannerCaption">
                    <h1>
                        BANYO SANATI
                    </h1>
                    <p>BİRAZ ŞIMARMAK HERKESİN HAKKI!</p>
                    <a class="detay2Bt" href="/detay/8/banyo-sanati-biraz-simarmak-herkesin" data-ga="banner2-click-id-8"></a>
                </div>
            </div>
        </div>
        <!-- end of slide -->
        <!-- new slide -->
        <div class="ms-slide">
            <!-- slide background -->
            <img src="/scripts/masterslider/blank.gif" data-src="/images/content/3_b.png" alt="" />
            <a href="/detay/38/dugunun-icin-ilham-al-orta-uzunluktaki" data-ga="banner3-click-id-38"></a>
            <!-- slide text layer -->
            <div class="ms-layer ms-caption" style="bottom:0px; left:30px;">
                <div class="bannerCaption">
                    <h1>
                        DÜĞÜNÜN İÇİN <br />
                        İLHAM AL
                    </h1>
                    <p>ORTA UZUNLUKTAKİ SAÇLAR İÇİN BOHEM DALGALAR</p>
                    <a class="detay2Bt" href="/detay/38/dugunun-icin-ilham-al-orta-uzunluktaki" data-ga="banner3-click-id-38"></a>
                </div>
            </div>
        </div>
        <!-- end of slide -->
    </div>
</div>

HairCare.Web/Views/Home/Index.cshtml
@section PageMetaOg {
    
    @Html.Partial("PageControls/PageMetaOg")
}


@Html.Action("HeroContents", "Home")

<div class="one_col_banner_area">
    <div class="content_inner">
        <div class="banner_one">
            <div class="banner_one_content_unit_wrapper">
                <div class="banner_one_content">
                    <h2 class="banner_one_desc_title">BANYO&nbsp;</h2>
                    <h2 class="banner_one_desc_title">RİTÜELİ</h2>
                    <p class="banner_one_desc">Ruh ve bedenin bütünleşerek içten gelen güzellikle buluştuğu tapınak...</p> <a class="detayBt" href="/sac-bakimi/banyo-ritueli" target="_self"></a>
                </div>
            </div>
        </div>
    </div>
</div>

@{Html.RenderAction("Recents", "Content");}

@{Html.RenderAction("MainPart", "Interview");}


<div class="populer_area"></div>
<script>
    $(document).ready(function () {
        var _popularPath = '/Content/Popular';
        $('.populer_area').load(_popularPath);        
    });
</script>

@{ Html.RenderAction("MainPart", "AskExpert"); }

@*<div class="stil_oneri_area">
    <div class="content_inner">

        <div data-foo="bar" id="container">
            <div id="filterNav" class="item stamp">
                <div id="filters">
                    <div class="stilFilter">
                        <div class="stil_title">
                            <h1 id="reset" style="cursor:pointer">
                                saç stil
                                önerileri
                            </h1>

                        </div>
                        <div class="tipi">
                            <h2>SAÇ TİPİ</h2>
                            <div style="text-align:center">
                                <input type="checkbox" class="radio" name="grp[1][]" value=".straight" id="straight">
                                <label for="straight"></label>
                                <input type="checkbox" class="radio" name="grp[1][]" value=".curly" id="curly">
                                <label for="curly"></label>
                                <input type="checkbox" class="radio" name="grp[1][]" value=".wavy" id="wavy">
                                <label for="wavy"></label>
                            </div>
                        </div>
                        <div class="uzunlugu">
                            <h2>UZUNLUĞU</h2>
                            <div style="text-align:center">
                                <input type="checkbox" class="radio" name="grp[2][]" value=".kisa" id="kisa">
                                <label for="kisa"></label>
                                <input type="checkbox" class="radio" name="grp[2][]" value=".orta" id="orta">
                                <label for="orta"></label>
                                <input type="checkbox" class="radio" name="grp[2][]" value=".uzun" id="uzun">
                                <label for="uzun"></label>
                            </div>
                        </div>
                        <div class="rengi">
                            <h2>RENGİ</h2>
                            <div style="text-align:center">
                                <input type="checkbox" class="radio" name="grp[3][]" value=".siyah" id="siyah">
                                <label for="siyah"></label>
                                <input type="checkbox" class="radio" name="grp[3][]" value=".kahverengi" id="kahverengi">
                                <label for="kahverengi"></label>
                                <input type="checkbox" class="radio" name="grp[3][]" value=".kizil" id="kizil">
                                <label for="kizil"></label>
                                <input type="checkbox" class="radio" name="grp[3][]" value=".sari" id="sari">
                                <label for="sari"></label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item straight">
                <img src="/images/sac_stilleri/01.jpg" />
            </div>
            <div class="item curly">
                <img src="/images/sac_stilleri/02.jpg" />
            </div>
            <div class="item wavy">
                <img src="/images/sac_stilleri/03.jpg" />
            </div>
            <div class="item kisa">
                <img src="/images/sac_stilleri/04.jpg" />
            </div>
            <div class="item orta">
                <img src="/images/sac_stilleri/05.jpg" />
            </div>
            <div class="item uzun">
                <img src="/images/sac_stilleri/06.jpg" />
            </div>
            <div class="item siyah">
                <img src="/images/sac_stilleri/07.jpg" />
            </div>
            <div class="item kahverengi">
                <img src="/images/sac_stilleri/08.jpg" />
            </div>
            <div class="item kizil">
                <img src="/images/sac_stilleri/09.jpg" />
            </div>
            <div class="item sari">
                <img src="/images/sac_stilleri/10.jpg" />
            </div>
        </div>


    </div>
</div>*@

@{Html.RenderAction("MainPart", "Tips");}

@{Html.RenderAction("MainPart", "StrongWomen");}
